services:
    sample-app-client:
        ports:
            - "8080:8080"
        depends_on:
            - sampleapp.api
    sampleapp.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTPS_PORTS=5001
        ports:
            - "5001:5001"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
